#!/usr/bin/env bash
#
# Prepare a fresh sandbox container (Claude Code on the web, Codex, Codespaces,
# CI-ish throwaway boxes) to build, test and run this repo.
#
# This is the single entry point for every agent/tool: `.claude/hooks/session-start.sh`
# calls it, and Codex should be pointed at it as its setup script. Safe to re-run.
#
# Node deps are required and a failure here aborts. The database is best effort:
# `yarn test` / `yarn check` / `yarn lint` all run without it (the worker tests
# use the in-memory fake in tests/worker/testUtils.ts), so a box with no Postgres
# still gets a usable session.
#
# Writes the environment it set up to `.dev-env` (gitignored). Source it before
# running `yarn dev`:  source ./.dev-env
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PG_DB="oy2"
PG_USER="$(id -un)"
PG_PASSWORD="oy2local" # local throwaway container only, never a real credential
DB_URL="postgres://${PG_USER}:${PG_PASSWORD}@127.0.0.1:5432/${PG_DB}"
ENV_FILE="$ROOT/.dev-env"

log() { printf '[dev-setup] %s\n' "$*"; }

# ---------------------------------------------------------------- node deps --
# Corepack fetches Yarn from repo.yarnpkg.com, which sandboxed egress policies
# tend to block. The npm registry is allowed far more often, and serves the same
# release.
export COREPACK_NPM_REGISTRY="${COREPACK_NPM_REGISTRY:-https://registry.npmjs.org}"
corepack enable >/dev/null 2>&1 || true

log "installing node dependencies"
yarn install

# ---------------------------------------------------------------- dev vars ---
if [ ! -f "$ROOT/.dev.vars" ]; then
	log "writing placeholder .dev.vars"
	cat > "$ROOT/.dev.vars" <<-'EOF'
		# Placeholders written by scripts/dev-setup.sh so `yarn dev` boots.
		# Every third-party integration below is inert with these values: email
		# codes (Resend), OAuth, geocoding and push will fail if exercised.
		JWT_SECRET=local-dev-secret
		VAPID_PUBLIC_KEY=local-dev-vapid-public
		VAPID_PRIVATE_KEY=local-dev-vapid-private
		VAPID_SUBJECT=mailto:dev@example.com
		RESEND_API_KEY=local-dev
		GOOGLE_MAPS_API_KEY=local-dev
	EOF
fi

# ----------------------------------------------------------------- postgres --
as_postgres() {
	if [ "$(id -u)" = "0" ]; then
		su postgres -c "$*"
	else
		sudo -n -u postgres bash -c "$*"
	fi
}

setup_postgres() {
	command -v psql >/dev/null 2>&1 || { log "no psql on PATH, skipping database"; return 1; }

	if ! pg_isready -q 2>/dev/null; then
		log "starting postgres"
		{ sudo -n service postgresql start || service postgresql start; } >/dev/null 2>&1 || true
	fi
	pg_isready -q 2>/dev/null || { log "postgres is not accepting connections, skipping database"; return 1; }

	if ! as_postgres "psql -tAc \"select 1 from pg_roles where rolname='${PG_USER}'\"" | grep -q 1; then
		log "creating role ${PG_USER}"
		as_postgres "createuser -s '${PG_USER}'"
	fi
	# workerd talks TCP, and TCP logins need a password even for a superuser.
	as_postgres "psql -qc \"alter role \\\"${PG_USER}\\\" with password '${PG_PASSWORD}'\"" >/dev/null

	if ! as_postgres "psql -tAc \"select 1 from pg_database where datname='${PG_DB}'\"" | grep -q 1; then
		log "creating database ${PG_DB}"
		as_postgres "createdb -O '${PG_USER}' '${PG_DB}'"
	fi

	log "applying migrations"
	DATABASE_URL="$DB_URL" yarn db:migrate:local
}

DB_READY=0
if setup_postgres; then
	DB_READY=1
else
	log "database unavailable — tests and linters still work, \`yarn dev\` will not"
fi

# ------------------------------------------------------------------- env -----
{
	echo "# Generated by scripts/dev-setup.sh — source this before \`yarn dev\`."
	echo "export COREPACK_NPM_REGISTRY=\"${COREPACK_NPM_REGISTRY}\""
	if [ "$DB_READY" = "1" ]; then
		echo "export DATABASE_URL=\"${DB_URL}\""
		echo "export CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE=\"${DB_URL}\""
		echo "export CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE_NO_CACHE=\"${DB_URL}\""
	fi
	# Wrangler routes *every* fetch through HTTPS_PROXY, including miniflare's
	# call to its own inspector on 127.0.0.1 — which egress proxies reject, and
	# the failure aborts `yarn dev`. Turning the inspector off avoids the call.
	if [ -n "${HTTPS_PROXY:-}${https_proxy:-}" ]; then
		echo "export DISABLE_WORKERD_INSPECTOR=1"
	fi
} > "$ENV_FILE"

# Claude Code sources this file into the session automatically.
if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
	cat "$ENV_FILE" >> "$CLAUDE_ENV_FILE"
fi

log "ready — env written to .dev-env"
